pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git branch: 'main', url: 'https://github.com/CarlaSantos18/devops-23-24-JPE-PMS-1231825.git'
            }
        }
        stage('Assemble') {
                    steps {
                        echo 'Assembling...'
                        dir('CA2/Part1/gradle_basic_demo'){
                            sh 'chmod +x gradlew'
                            sh './gradlew clean assemble'
                        }
                    }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                dir('CA2/Part1/gradle_basic_demo'){
                sh './gradlew test'
                }
            }
            post {
                always {
                    junit 'CA2/Part1/gradle_basic_demo/build/test-results/test/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                echo 'Archiving...'
                archiveArtifacts 'CA2/Part1/gradle_basic_demo/build/distributions/*'
            }
        }
    }
}
